### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by salaiviswatech** [ngx-translate/i18n-polyfill#49]
Hi,

I am using i18n polyfill in my angular6 project.  when I run the below command in my project, 
package.json Setting:
`"extract-i18n": "ng xi18n --i18n-format=xlf --output-path i18n && ngx-extractor -i \"./src/**/*.ts\" -o src/i18n/messages.xlf --format=xlf && xliffmerge --profile xliffmerge.json en cy"`

I am getting the below error:
```
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at files.forEach.path (C:\Repos\MyProject\node_modules\@ngx-translate\i18n-polyfill\extractor\src\extractor.js:22:35)
    at Array.forEach (<anonymous>)
    at Object.getAst (C:\Repos\MyProject\node_modules\@ngx-translate\i18n-polyfill\extractor\src\extractor.js:19:11)
    at main (C:\Repos\MyProject\node_modules\@ngx-translate\i18n-polyfill\extractor\ngx-extractor.js:51:34)
    at Object.<anonymous> (C:\Repos\MyProject\node_modules\@ngx-translate\i18n-polyfill\extractor\ngx-extractor.js:63:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adviserui@1.0.0 extract-i18n: `ng xi18n --i18n-format=xlf --output-path i18n && ngx-extractor -i "./src/**/*.ts" -o src/i18n/messages.xlf --format=xlf && xliffmerge --profile xliffmerge.json en cy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Myproject@1.0.0 extract-i18n script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{UserName}\AppData\Roaming\npm-cache\_logs\2019-01-17T06_11_25_320Z-debug.log 
```
Can you tell me why this error occurring? Please let me know if any details required on this.

**Comment by salaiviswatech** [comment]
I found the issue. In my project, one of the directory is named as "model.ts" and hence the command got broken. Once, I fixed that, it worked fine.

**Comment by salaiviswatech** [comment]
It would be better if the error log could highlight the file path in order to fix the issue manually.
